volodya-lombrozo/jtcop

src/main/java/com/github/lombrozo/testnames/JavaTestCode.java

Add context for exception during Java parsing

feat(#4): add exception context for JavaTestCode

---

README.md

Add more information about the project to `README`
Closes: #2

doc(#2): Add samples into README

---

pom.xml
src/main/java/com/github/lombrozo/testnames/ValidateMojo.java

Add filter for `java` files only:
```java
filter(path -> path.toString().endsWith(".java"))
```

fix(#4): add filter for `java` files only

---

src/main/java/com/github/lombrozo/testnames/Rule.java
src/main/java/com/github/lombrozo/testnames/TestCase.java
src/main/java/com/github/lombrozo/testnames/ValidateMojo.java
src/main/java/com/github/lombrozo/testnames/javaparser/JavaParserCase.java
src/main/java/com/github/lombrozo/testnames/javaparser/JavaTestCode.java
src/main/java/com/github/lombrozo/testnames/javaparser/package-info.java
src/main/java/com/github/lombrozo/testnames/rules/AllTestsInPresentSimple.java
src/main/java/com/github/lombrozo/testnames/rules/CompositeTestPathRule.java
src/main/java/com/github/lombrozo/testnames/rules/NotCamelCase.java
src/main/java/com/github/lombrozo/testnames/rules/NotContainsTestWord.java
src/main/java/com/github/lombrozo/testnames/rules/NotSpam.java
src/main/java/com/github/lombrozo/testnames/rules/NotUsesSpecialCharacters.java
src/main/java/com/github/lombrozo/testnames/rules/PresentSimpleRule.java
src/main/java/com/github/lombrozo/testnames/rules/PresentTense.java
src/main/java/com/github/lombrozo/testnames/rules/package-info.java
src/test/java/com/github/lombrozo/testnames/javaparser/JavaTestCodeTest.java
src/test/java/com/github/lombrozo/testnames/javaparser/package-info.java
src/test/java/com/github/lombrozo/testnames/package-info.java
src/test/java/com/github/lombrozo/testnames/rules/AllTestsInPresentSimpleTest.java
src/test/java/com/github/lombrozo/testnames/rules/CompositeTestPathRuleTest.java
src/test/java/com/github/lombrozo/testnames/rules/CorrectCases.java
src/test/java/com/github/lombrozo/testnames/rules/RuleTest.java
src/test/java/com/github/lombrozo/testnames/rules/WrongCases.java
src/test/java/com/github/lombrozo/testnames/rules/package-info.java

Move classes into corresponding packages
Closes: #14

feat(#14): move classes into separate packages

---

src/main/java/com/github/lombrozo/testnames/rules/NotContainsTestWord.java
src/test/java/com/github/lombrozo/testnames/rules/NotContainsTestWordTest.java

Add test and simplify implementation.
Closes: #3

fix(#3): Check word 'test' more carefully

---

pom.xml
src/test/java/com/github/lombrozo/testnames/javaparser/JavaTestCodeTest.java
src/test/java/com/github/lombrozo/testnames/rules/CompositeTestPathRuleTest.java

Apply `test-names-conventions` plugin to itself
Closes: #17

feat(#17): apply `test-names-conventions` plugin to itself

---

pom.xml

Upgrade version in pom up to 0.1.7

Upgrade version in pom up to 0.1.7

---

.rultor.yml

fix: try to fix rultor config

---

pom.xml

Add JaCoCo plugin.
Closes: #18

feat(#18): add JaCoCoo plugin

---

.rultor.yml
pom.xml

Ingore plugins for version:set

Fix Rultor release pipeline

---

pom.xml
src/main/java/com/github/lombrozo/testnames/javaparser/JavaTestCode.java
src/test/java/com/github/lombrozo/testnames/javaparser/JavaTestCodeTest.java

Make `JavaTestCode` accept `IntputStream` in the constructor.

Refactor `JavaTestCode`

---

src/main/java/com/github/lombrozo/testnames/Complaint.java
src/main/java/com/github/lombrozo/testnames/TestClass.java
src/main/java/com/github/lombrozo/testnames/complaints/CompoundClassComplaint.java
src/main/java/com/github/lombrozo/testnames/javaparser/JavaParserTestClass.java
src/main/java/com/github/lombrozo/testnames/rules/AllTestsInPresentSimple.java
src/test/java/com/github/lombrozo/testnames/complaints/CompoundClassComplaintTest.java
src/test/java/com/github/lombrozo/testnames/rules/AllTestsInPresentSimpleTest.java
src/test/java/com/github/lombrozo/testnames/rules/CompositeTestPathRuleTest.java

Add `CompoundClassComplaint` to handle all class complaints.

Add CompoundClassComplaint class.

---

src/main/java/com/github/lombrozo/testnames/Cop.java
src/main/java/com/github/lombrozo/testnames/ProductionClass.java
src/main/java/com/github/lombrozo/testnames/Project.java
src/main/java/com/github/lombrozo/testnames/TestCase.java
src/main/java/com/github/lombrozo/testnames/TestClass.java
src/main/java/com/github/lombrozo/testnames/ValidateMojo.java
src/main/java/com/github/lombrozo/testnames/complaints/CompoundClassComplaint.java
src/main/java/com/github/lombrozo/testnames/javaparser/JavaParserProductionClass.java
src/main/java/com/github/lombrozo/testnames/javaparser/JavaParserProject.java
src/main/java/com/github/lombrozo/testnames/rules/AllTestsHaveProductionClassRule.java
src/main/java/com/github/lombrozo/testnames/rules/AllTestsInPresentSimple.java
src/test/java/com/github/lombrozo/testnames/CopTest.java
src/test/java/com/github/lombrozo/testnames/javaparser/JavaParserProductionClassTest.java
src/test/java/com/github/lombrozo/testnames/javaparser/JavaParserProjectTest.java
src/test/java/com/github/lombrozo/testnames/rules/AllTestsHaveProductionClassRuleTest.java

Check that all tests have corresponding production class.

Check class names

---

src/it/all-have-production-class/pom.xml
src/it/all-have-production-class/src/test/java/CorrectTest.java
src/it/all-have-production-class/verify.groovy
src/main/java/com/github/lombrozo/testnames/complaints/ClassComplaint.java
src/main/java/com/github/lombrozo/testnames/rules/AllTestsHaveProductionClassRule.java
src/main/java/com/github/lombrozo/testnames/rules/AllTestsInPresentSimple.java
src/test/java/com/github/lombrozo/testnames/complaints/ClassComplaintTest.java
src/test/java/com/github/lombrozo/testnames/rules/AllTestsHaveProductionClassRuleTest.java

Add integration test for `AllTestsHaveProductionClassRule`

feat: add integration test for `AllTestsHaveProductionClassRule`

---

src/it/all-have-production-class/verify.groovy
src/main/java/com/github/lombrozo/testnames/complaints/ClassComplaint.java
src/main/java/com/github/lombrozo/testnames/rules/AllTestsHaveProductionClassRule.java
src/test/java/com/github/lombrozo/testnames/complaints/ClassComplaintTest.java
src/test/java/com/github/lombrozo/testnames/rules/AllTestsHaveProductionClassRuleTest.java

Reformat text messages and ignore `package-info.java` in tests

Small fixes

---

README.md
docs/README.md
docs/rules/camel-case.md
docs/rules/present-tense.md

Add small documentation skeleton

chore: add small documentation skeleton

---

src/main/java/com/github/lombrozo/testnames/javaparser/JavaParserProductionClass.java
src/main/java/com/github/lombrozo/testnames/rules/AllTestsHaveProductionClassRule.java
src/test/java/com/github/lombrozo/testnames/rules/AllTestsHaveProductionClassRuleTest.java

Handle classes with .java extensions correctly

Handle classes with .java extensions correctly

---

src/main/java/com/github/lombrozo/testnames/rules/RuleAllTestsHaveProductionClass.java

chore: add puzzle for documentation

---

src/main/java/com/github/lombrozo/testnames/TestClass.java
src/main/java/com/github/lombrozo/testnames/javaparser/TestCaseJavaParser.java
src/main/java/com/github/lombrozo/testnames/javaparser/TestClassJavaParser.java
src/test/java/com/github/lombrozo/testnames/javaparser/TestClassJavaParserTest.java
src/test/resources/TestWithSuppressed.java

Add support for suppressed annotations for java classes.

feat(#78): Add support for suppressed annotations for java classes.

---

src/main/java/com/github/lombrozo/testnames/Cop.java
src/main/java/com/github/lombrozo/testnames/javaparser/TestCaseJavaParser.java
src/main/java/com/github/lombrozo/testnames/javaparser/TestClassJavaParser.java
src/test/java/com/github/lombrozo/testnames/javaparser/TestClassJavaParserTest.java
src/test/resources/TestWithLotsOfSuppressed.java

Handle corner cases for `TestClass#suppressed()`, added correct implementation into `TestCaseJavaParser`

feat(#110): Handle corner cases for `TestClass#suppressed()` 

---

src/it/all-have-production-class/src/test/java/SuppressedTest.java
src/main/java/com/github/lombrozo/testnames/Cop.java
src/main/java/com/github/lombrozo/testnames/Rule.java
src/main/java/com/github/lombrozo/testnames/TestClass.java
src/main/java/com/github/lombrozo/testnames/rules/RuleAllTestsHaveProductionClass.java
src/test/java/com/github/lombrozo/testnames/rules/RuleAllTestsHaveProductionClassTest.java

implement suppress for `RuleAllTestsHaveProductionClass`
Closes: #114

feat(#114): implement suppress for `RuleAllTestsHaveProductionClass`

---

src/main/java/com/github/lombrozo/testnames/javaparser/SuppressedAnnotations.java
src/main/java/com/github/lombrozo/testnames/javaparser/TestCaseJavaParser.java
src/main/java/com/github/lombrozo/testnames/javaparser/TestClassJavaParser.java
src/test/java/com/github/lombrozo/testnames/javaparser/TestCaseJavaParserTest.java
src/test/java/com/github/lombrozo/testnames/javaparser/TestClassJavaParserTest.java
src/test/resources/TestWithLotsOfSuppressed.java

Implementation for suppressing of methods in a java class.
Closes: #115

feat(#115): Suppress rules in methods

---

src/main/java/com/github/lombrozo/testnames/Cop.java
src/main/java/com/github/lombrozo/testnames/Rule.java
src/main/java/com/github/lombrozo/testnames/TestCase.java
src/main/java/com/github/lombrozo/testnames/TestClass.java
src/main/java/com/github/lombrozo/testnames/rules/RuleAllTestsHaveProductionClass.java
src/main/java/com/github/lombrozo/testnames/rules/RuleAllTestsInPresentSimple.java
src/main/java/com/github/lombrozo/testnames/rules/RulePresentSimple.java
src/main/java/com/github/lombrozo/testnames/rules/RuleSuppressed.java
src/test/java/com/github/lombrozo/testnames/rules/RuleAllTestsHaveProductionClassTest.java
src/test/java/com/github/lombrozo/testnames/rules/RuleAllTestsInPresentSimpleTest.java

Implement RuleSuppressed rule that checks whether delegated rule is suppressed. The current solution isn't perfect, but I've added several puzzles to finish the implementation.
Closes: #117

feat(#117): Add implementation of RuleSuppressed

---

docs/rules/all-have-production-class.md
src/main/java/com/github/lombrozo/testnames/rules/RuleAllTestsHaveProductionClass.java

Add documentation for `RuleAllTestsHaveProductionClass `.
Closes: #103

doc(#103): Add documentation for RuleAllTestsHaveProductionClass

---

src/main/java/com/github/lombrozo/testnames/TestClass.java
src/main/java/com/github/lombrozo/testnames/ValidateMojo.java
src/main/java/com/github/lombrozo/testnames/javaparser/ProjectJavaParser.java
src/main/java/com/github/lombrozo/testnames/javaparser/TestCaseJavaParser.java
src/main/java/com/github/lombrozo/testnames/javaparser/TestClassJavaParser.java
src/test/java/com/github/lombrozo/testnames/javaparser/TestCaseJavaParserTest.java
src/test/java/com/github/lombrozo/testnames/javaparser/TestClassJavaParserTest.java
src/test/resources/TestOnlyMethodsSuppressed.java

All project exclusions cancel rules execution for its classes and methods.
All class suppressed rules cancel rules execution for all its methods.
Closes: #129

feat(#129): Tree Like Suppression

---

.github/workflows/maven.test.yaml

bug(#530): ubuntu version up
